### ISSUE TITLE
Test fail on arm64 and armhf systems

### ISSUE THREAD

**Issue by mr-c** [PeteHaitch/DelayedMatrixStats#67]
Hello,

Volunteers with the Debian project have recently packaged DelayedMatrixStats as `r-bioc-delayedmatrixstats` for Debian. While running the included tests, we noticed they fail on some architectures, specifically [arm64](https://wiki.debian.org/Arm64Port) and [armhf](https://wiki.debian.org/ArmHardFloatPort).

`[ FAIL 30 | WARN 0 | SKIP 0 | PASS 14690 ]`

Full logs: 
https://ci.debian.net/data/autopkgtest/testing/arm64/r/r-bioc-delayedmatrixstats/8234322/log.gz

https://ci.debian.net/data/autopkgtest/testing/armhf/r/r-bioc-delayedmatrixstats/8234519/log.gz

Example failure

```
> test_check("DelayedMatrixStats")
Loading required package: rhdf5
── FAILURE (test_row_and_col_functions.R:49:5): Default arguments ──────────────
c(0L, 0L, 0L, 0L) not equal to c(NA_integer_, NA_integer_, NA_integer_, NA_integer_).
4/4 mismatches (average diff: NaN)
[1] 0 - NA == NA
[2] 0 - NA == NA
[3] 0 - NA == NA
[4] 0 - NA == NA
```
Any patches to fix this (or a new release) would be greatly appreciated!

Many thanks for contributing scientific open source software.

**Comment by mr-c** [comment]
I see that sparseMatrixStats has a very similar pattern of failure, so I'm guessing the real issue is there: https://github.com/const-ae/sparseMatrixStats/issues/16

**Comment by PeteHaitch** [comment]
Hi @mr-c, thanks for the report. I rely on the Bioconductor build machines and aim to pass their checks (http://bioconductor.org/checkResults/devel/bioc-LATEST/DelayedMatrixStats/). These are all x86_64/x64 architectures, I believe, which is why I've never seen these test errors.

I'm willing to try to fix but I don't have access to machines running these architectures. Any suggestions on where I could access a (virtual?) machine?

Also, as you note, this error may be from deeper in the dependency chain - two possibilities that spring to mind are **sparseMatrixStats** (Bioconductor) or **matrixStats** (CRAN, https://cran.r-project.org/package=matrixStats). But my reading of the **matrixStats** logs are that it's fine (https://ci.debian.net/data/autopkgtest/testing/arm64/r/r-cran-matrixstats/8182289/log.gz)

**Comment by mr-c** [comment]
> I'm willing to try to fix but I don't have access to machines running these architectures. Any suggestions on where I could access a (virtual?) machine?

If you have access to a Debian machine, then you can test using qemu

I can also put together a Dockerfile that builds the package using qemu

A Raspberry Pi also works, especially if you install a 64 bit operating system on the Raspberry PI4 (which would give you arm64)

There are general pointers at https://github.com/simd-everywhere/simde/wiki/Development-Environment#arm but it is probably easier for me to put together a Dockefile for you.

**Comment by mr-c** [comment]
And yes, I agree that the real problem may lie with `sparseMatrixStats` : https://ci.debian.net/data/autopkgtest/testing/arm64/r/r-bioc-sparsematrixstats/7988852/log.gz

**Comment by mr-c** [comment]
At some point I can also help you add an `arm64` build to your `.travis.yml` Travis-CI configuration.

**Comment by LTLA** [comment]
See commentary in #70.

**Comment by mr-c** [comment]
@LTLA Thanks! I've [asked](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=979353) the relevant Debian maintainer to update our r-cran-matrix package to 1.3-2

**Comment by LTLA** [comment]
Ah. I don't think it's out yet. We're also waiting for it in the BioC build system.

@PeteHaitch It may be faster to just change the tests to avoid creating `ddiMatrix` objects for the time being.

**Comment by PeteHaitch** [comment]
Thanks. I've been camping since Christmas without laptop/reception but I'll be back next week and deal with these issues

**Comment by PeteHaitch** [comment]
Closing this as [recent builds seem to be working](https://ci.debian.net/data/autopkgtest/testing/arm64/r/r-bioc-delayedmatrixstats/9630413/log.gz), but let me know if I've misunderstood, @mr-c. Thanks.

**Comment by mr-c** [comment]
Thanks! Yeah, still waiting for armhf and ppc64el to run, but I have a good feeling about them

https://qa.debian.org/excuses.php?package=r-bioc-delayedmatrixstats
