### ISSUE TITLE
Why does this depend on HDF5Array?

### ISSUE THREAD

**Issue by LTLA** [PeteHaitch/DelayedMatrixStats#72]
Apparently it never gets used, according to [the CHECK notes](http://bioconductor.org/checkResults/devel/bioc-LATEST/DelayedMatrixStats/malbec2-checksrc.html). Also **BiocParallel**. Seems like both of these should be moved to the `Suggests`, which would slim down the dependencies for all DMS's client packages.

**Comment by PeteHaitch** [comment]
Fair question. A grep shows there are some examples and tests that use **HDF5Array** but I can't see anything using **BiocParallel**. I'll take a look during the week to see if it can slim down the dependencies

**Comment by LTLA** [comment]
Should be sufficient to move one or both to Suggests. HDF5Array in particular should not be a hard requirement.

**Comment by PeteHaitch** [comment]
Done in dec47a286cf451b40dabcc9285f4f8efc89f78e4
