### ISSUE TITLE
Fail to install version 1.12.2

### ISSUE THREAD

**Issue by derbalkon** [PeteHaitch/DelayedMatrixStats#73]
Hi, I'm getting some troubles installing version 1.12.2 recently. Every time I try to install the latest `DelayedMatrixStats` package, it always prompts up these error messages:

```R
* installing *source* package ‘DelayedMatrixStats’ ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Error : in method for ‘colAvgsPerRowSet’ with signature ‘X="DelayedMatrix"’:  arguments (‘na.rm’, ‘tFUN’) after ‘...’ in the generic must appear in the method, in the same place at the end of the argument list
Error: unable to load R code in package ‘DelayedMatrixStats’
Execution halted
ERROR: lazy loading failed for package ‘DelayedMatrixStats’
* removing ‘/usr/local/lib/R/4.0/site-library/DelayedMatrixStats’
* restoring previous ‘/usr/local/lib/R/4.0/site-library/DelayedMatrixStats’
```

Here's my session info:

```R
R version 4.0.3 (2020-10-10)
Platform: x86_64-apple-darwin20.2.0 (64-bit)
Running under: macOS  11.1

Matrix products: default
BLAS:   /usr/local/Cellar/openblas/0.3.13/lib/libopenblasp-r0.3.13.dylib
LAPACK: /usr/local/Cellar/r/4.0.3_2/lib/R/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.0.3
```

I have also tried to install it on a new virtual machine, still no luck. Then I checked the [build report](http://bioconductor.org/checkResults/3.12/bioc-LATEST/DelayedMatrixStats/) page, found the multiple platform builds are all failed with the same errors as mine. Perhaps something related to dependency has changed lately?

**Comment by renozao** [comment]
Also have this issue.
The method definition must be edited to match the generic in package `MatrixGenerics`:

```R
setGeneric("colAvgsPerRowSet", function(X, W = NULL, cols = NULL, S, FUN = colMeans,  ..., na.rm = NA, tFUN = FALSE) standardGeneric("colAvgsPerRowSet"),
           signature = "X"
)
```

Currently the method is defined as follows, so one would need to add argument `na.rm`:

```R
setMethod("colAvgsPerRowSet", "DelayedMatrix",
          function(X, W = NULL, cols = NULL, S, FUN = colMeans, ...,
                   force_block_processing = FALSE, tFUN = FALSE) {
# ...
}
```

**Comment by PeteHaitch** [comment]
I'm on leave but I'll take a look when back on Friday.

**Comment by PeteHaitch** [comment]
@hpages would you be able to fix this before then? I think it would need to be patched in release and devel

**Comment by bbimber** [comment]
We're hitting this as well

**Comment by XimenaBo** [comment]
Hi, has this been fixed, by any chance?
Thanks!

**Comment by bbimber** [comment]
If anyone wants a stopgap, I think this is a fix:

devtools::install_version("bbimber/DelayedMatrixStats", ref = "RELEASE_3_12")

Here's a PR #75. I dont know what it takes to push out a new version. @PeteHaitch @hpages - it seems like a lot of people would appreciate if there's a way to push a fixed version.

**Comment by rschauner** [comment]
> If anyone wants a stopgap, I think this is a fix:
> 
> devtools::install_version("bbimber/DelayedMatrixStats", ref = "RELEASE_3_12")
> 
> Here's a PR #75. I dont know what it takes to push out a new version. @PeteHaitch @hpages - it seems like a lot of people would appreciate if there's a way to push a fixed version.

Thanks for your quick workaround. Trying to set up an HPC to run what I need to and this was the last thing I needed to install. However, I did need to change your code to this `devtools::install_github("bbimber/DelayedMatrixStats", ref = "RELEASE_3_12")` to get it to work.

**Comment by XimenaBo** [comment]
> Thanks for your quick workaround. Trying to set up an HPC to run what I need to and this was the last thing I needed to install. However, I did need to change your code to this `devtools::install_github("bbimber/DelayedMatrixStats", ref = "RELEASE_3_12")` to get it to work.

Awesome, thank you both!

**Comment by bbimber** [comment]
yeah, should have been install_github. I've done little testing of my change, but it does at least build.

**Comment by hpages** [comment]
I pushed Aaron's fix today to the git repo hosted at `git.bioconductor.org`. Will take about 36 hours to propagate and become available via `BiocManager::install()`. If you can't wait, you can get this new version by cloning `https://git.bioconductor.org/packages/DelayedMatrixStats`.

Remember to switch to the `RELEASE_3_12` branch (**DelayedMatrixStats** 1.12.3) if you're using BioC 3.12 (current release). The `master` branch (**DelayedMatrixStats** 1.13.5) is for BioC devel only.

@PeteHaitch Don't forget to resync the GitHub repo when you are back.

H.

**Comment by PeteHaitch** [comment]
Thanks, @LTLA for the PR and @hpages for pushing to `git.bioconductor.org`. I've been able to sync with GitHub as I'm back from camping a little earlier than originally planned.
