### ISSUE TITLE
Failed to download DelayedMatrixStats

### ISSUE THREAD

**Issue by RunhangShu** [PeteHaitch/DelayedMatrixStats#78]
Hello, I tried to download DelayedMatrixStats in Windows but R gave me errors. 

> BiocManager::install("DelayedMatrixStats")
**Bioconductor version 3.12 (BiocManager 1.30.10), R 4.0.1 (2020-06-06)**
Installing package(s) 'DelayedMatrixStats'

  There is a binary version available but the source version is later:
                   binary source needs_compilation
DelayedMatrixStats 1.12.1 1.12.2             FALSE

installing the source package ‘DelayedMatrixStats’

trying URL 'https://bioconductor.org/packages/3.12/bioc/src/contrib/DelayedMatrixStats_1.12.2.tar.gz'
Content type 'application/x-gzip' length 271694 bytes (265 KB)
downloaded 265 KB

* installing *source* package 'DelayedMatrixStats' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Warning messages:
1: package 'MatrixGenerics' was built under R version 4.0.3 
2: package 'matrixStats' was built under R version 4.0.3 
3: package 'DelayedArray' was built under R version 4.0.3 
4: package 'Matrix' was built under R version 4.0.3 
5: package 'BiocGenerics' was built under R version 4.0.3 
6: package 'S4Vectors' was built under R version 4.0.3 
7: package 'IRanges' was built under R version 4.0.3 
Error : in method for 'colAvgsPerRowSet' with signature 'X="DelayedMatrix"':  arguments ('na.rm', 'tFUN') after '...' in the generic must appear in the method, in the same place at the end of the argument list
Error: unable to load R code in package 'DelayedMatrixStats'
Execution halted
ERROR: lazy loading failed for package 'DelayedMatrixStats'
* removing 'C:/Users/r.shu/Documents/R/R-4.0.1/library/DelayedMatrixStats'

The downloaded source packages are in
	‘C:\Users\r.shu\AppData\Local\Temp\Rtmpk5Hjrh\downloaded_packages’
Old packages: 'backports', 'Matrix', 'MSnbase', 'systemfonts'
Update all/some/none? [a/s/n]: 
a

  There are binary versions available but the source versions are later:
            binary source needs_compilation
backports    1.2.0  1.2.1              TRUE
Matrix      1.2-18  1.3-2              TRUE
MSnbase     2.15.7 2.16.1              TRUE
systemfonts  0.3.2  1.0.0              TRUE

  Binaries will be installed
trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/backports_1.2.0.zip'
Content type 'application/zip' length 98138 bytes (95 KB)
downloaded 95 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/Matrix_1.2-18.zip'
Content type 'application/zip' length 4506373 bytes (4.3 MB)
downloaded 4.3 MB

trying URL 'https://bioconductor.org/packages/3.12/bioc/bin/windows/contrib/4.0/MSnbase_2.15.7.zip'
Content type 'application/zip' length 7465342 bytes (7.1 MB)
downloaded 7.1 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/systemfonts_0.3.2.zip'
Content type 'application/zip' length 1507424 bytes (1.4 MB)
downloaded 1.4 MB

package ‘backports’ successfully unpacked and MD5 sums checked
package ‘Matrix’ successfully unpacked and MD5 sums checked
package ‘MSnbase’ successfully unpacked and MD5 sums checked
package ‘systemfonts’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\r.shu\AppData\Local\Temp\Rtmpk5Hjrh\downloaded_packages
**Warning message:
In install.packages(...) :
  installation of package ‘DelayedMatrixStats’ had non-zero exit status**

Then, I tried to download it from github. But it wont work. 
> devtools::install_github('https://github.com/PeteHaitch/DelayedMatrixStats')
Downloading GitHub repo PeteHaitch/DelayedMatrixStats@HEAD
√  checking for file 'C:\Users\r.shu\AppData\Local\Temp\Rtmpk5Hjrh\remotes24841b0d4c13\PeteHaitch-DelayedMatrixStats-ab16682/DESCRIPTION' ...
-  preparing 'DelayedMatrixStats': (451ms)
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
   Removed empty directory 'DelayedMatrixStats/longtests'
-  building 'DelayedMatrixStats_1.13.5.tar.gz'
   
* installing *source* package 'DelayedMatrixStats' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Error: (converted from warning) package 'MatrixGenerics' was built under R version 4.0.3
Execution halted
ERROR: lazy loading failed for package 'DelayedMatrixStats'
* removing 'C:/Users/r.shu/Documents/R/R-4.0.1/library/DelayedMatrixStats'
Error: Failed to install 'DelayedMatrixStats' from GitHub:
  (converted from warning) installation of package ‘C:/Users/r.shu/AppData/Local/Temp/Rtmpk5Hjrh/file248426c82e22/DelayedMatrixStats_1.13.5.tar.gz’ had non-zero exit status

> sessionInfo()
R version 4.0.1 (2020-06-06)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] rstudioapi_0.13     magrittr_2.0.1      usethis_2.0.0       devtools_2.3.2      pkgload_1.1.0       R6_2.5.0           
 [7] rlang_0.4.10        fastmap_1.1.0       tools_4.0.1         pkgbuild_1.2.0      xfun_0.20           sessioninfo_1.1.1  
[13] tinytex_0.29        cli_2.3.0           withr_2.4.1         ellipsis_0.3.1      remotes_2.2.0       assertthat_0.2.1   
[19] rprojroot_2.0.2     lifecycle_0.2.0     crayon_1.4.0        processx_3.4.5      purrr_0.3.4         BiocManager_1.30.10
[25] callr_3.5.1         fs_1.5.0            ps_1.5.0            curl_4.3            testthat_3.0.1      memoise_2.0.0      
[31] glue_1.4.2          cachem_1.0.1        compiler_4.0.1      desc_1.2.0          prettyunits_1.1.1

Thanks in advance!

**Comment by LTLA** [comment]
See #73.
