### ISSUE TITLE
Installation of package ‘DelayedMatrixStats’ had non-zero exit status

### ISSUE THREAD

**Issue by stephen-siecinski** [PeteHaitch/DelayedMatrixStats#86]
Encountering the same issue described in [this previously closed thread](https://github.com/PeteHaitch/DelayedMatrixStats/issues/78) 

As demonstrated below

In the previously linked thread, the workaround using devtools no longer works. I've also tried downloading the package directly and installing from the .tar file but that failed with the same error. If anyone is still encountering this issue and found a workaround I would greatly appreciate! 

```
BiocManager::install("DelayedMatrixStats")
Bioconductor version 3.13 (BiocManager 1.30.16), R 4.1.0 (2021-05-18)
Installing package(s) 'DelayedMatrixStats'
trying URL 'https://bioconductor.org/packages/3.13/bioc/src/contrib/DelayedMatrixStats_1.14.0.tar.gz'
Content type 'application/x-gzip' length 278010 bytes (271 KB)
==================================================
downloaded 271 KB

* installing *source* package ‘DelayedMatrixStats’ ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Error : in method for ‘colAlls’ with signature ‘x="DelayedMatrix"’:  arguments (‘useNames’) after ‘...’ in the generic must appear in the method, in the same place at the end of the argument list
Error: unable to load R code in package ‘DelayedMatrixStats’
Execution halted
ERROR: lazy loading failed for package ‘DelayedMatrixStats’
* removing ‘######’

The downloaded source packages are in
        ‘/tmp/RtmpjdMFQQ/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning message:
In .inet_warning(msg) :
  installation of package ‘DelayedMatrixStats’ had non-zero exit status
```

**Comment by edroaldo** [comment]
I am having the same issue. Any help, please? Thank you!

**Comment by stephen-siecinski** [comment]
I was able to get it to work using the previous version with devtools as a temporary workaround 

devtools::install_github("PeteHaitch/DelayedMatrixStats@RELEASE_3_13")

**Comment by edroaldo** [comment]
Thanks! That solved my issue!

**Comment by PeteHaitch** [comment]
Updated versions are now available from Bioconductor using `BiocManager::install("DelatedMatrixStats")

**Comment by tryggest** [comment]
This error seems to be back

**Comment by PeteHaitch** [comment]
Please start a new issue, including the commands you used to install **DelayedMatrixStats**, its output, and the output of running `BiocManager::valid()`
