### ISSUE TITLE
Please use consistent signing in version numbers

### ISSUE THREAD

**Issue by tillea** [PeteHaitch/DelayedMatrixStats#88]
Hi,
when I updated the Debian packaged version of DelayedMatrixStats I realised that the versioned dependency from the Matrix package was specified as "(>= 1.5.0)" while the Matrix package you are referring to is actually 1.5-0 (with a '-' sign, not a dot).  I'm perfectly aware that R is sorting '.' and '-' is sorting equally.  However, in other environments where this is not the case it is asking for trouble when using divergent spelling of the version string.  That's why I applied a [patch](https://salsa.debian.org/r-pkg-team/r-bioc-delayedmatrixstats/-/blob/master/debian/patches/fix_version_separation_sign.patch) to the Debian package which boils down to

    -        (>= 1.5.0), S4Vectors (>= 0.17.5), IRanges (>= 2.25.10)
    +        (>= 1.5-0), S4Vectors (>= 0.17.5), IRanges (>= 2.25.10)

inside the DESCRIPTION file.  It would be great if you could apply this to the next release.
Kind regards, Andreas.

**Comment by PeteHaitch** [comment]
Thanks for bringing this to my attention, @tillea.
I didn't know there were R packages that used '-' as a delimiter in version numbers.
I've updated it in the development and release branches of Bioconductor.
New versions should be available via the Bioconductor build system in the next 24-48 hours.

**Comment by tillea** [comment]
Am Tue, Oct 11, 2022 at 02:33:42PM -0700 schrieb Peter Hickey:
> Thanks for bringing this to my attention, @tillea.

Thanks for closing this quickly.

> I didn't know there were R packages that used '-' as a delimiter in version numbers.

Several years ago we replaced '-' by '.' but this turned out as
a failure for several reasons.

> I've updated it in the development and release branches of Bioconductor.
> New versions should be available via the Bioconductor build system in the next 24-48 hours.

There is no hurry needed actually since I've solved the issue with the
patch.  For future releases your change is very convenient.

Thanks a lot for the cooperation, Andreas.
