### ISSUE TITLE
ERROR: compilation failed for package 'DelayedArray'

### ISSUE THREAD

**Issue by chen-peng-1874** [PeteHaitch/DelayedMatrixStats#89]
I am trying to install "celldex" for annotation, before which I need to install "DelayedArray". And the error happeded.
Has anyone met this before? How to solve this problem?

ps. My R version is the latest.
this is my code: 
**_if (!require("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
BiocManager::install("celldex")_**

Thank you！

**Comment by PeteHaitch** [comment]
What version of R and Bioconductor are you using?
What operating system are you on?
Please post the output of `BiocManager::valid()` and the full output of the code from your initial post.

**Comment by PeteHaitch** [comment]
The package is building fine on the Bioconductor build system, so I'll need more information to be able to help,

[3.16](https://www.bioconductor.org/checkResults/3.16/bioc-LATEST/DelayedMatrixStats/)
[3.17](https://www.bioconductor.org/checkResults/3.17/bioc-LATEST/DelayedMatrixStats/)

**Comment by chen-peng-1874** [comment]
> What version of R and Bioconductor are you using? What operating system are you on? Please post the output of `BiocManager::valid()` and the full output of the code from your initial post.

```r
Bioconductor version 3.16 (BiocManager 1.30.19), R 4.2.2 (2022-10-31 ucrt).
here it is:
 **_BiocManager::install("celldex")
'getOption("repos")' replaces Bioconductor standard repositories, see '?repositories' for details

replacement repositories:
    CRAN: https://cran.rstudio.com/

Bioconductor version 3.16 (BiocManager 1.30.19), R 4.2.2 (2022-10-31 ucrt)
Installing package(s) 'celldex'
also installing the dependency ‘DelayedArray’


  There is a binary version available but the source version is later:
             binary source needs_compilation
DelayedArray 0.23.2 0.24.0              TRUE

installing the source packages ‘DelayedArray’, ‘celldex’

trying URL 'https://bioconductor.org/packages/3.16/bioc/src/contrib/DelayedArray_0.24.0.tar.gz'
Content type 'application/x-gzip' length 642972 bytes (627 KB)
downloaded 627 KB

trying URL 'https://bioconductor.org/packages/3.16/data/experiment/src/contrib/celldex_1.8.0.tar.gz'
Content type 'application/x-gzip' length 389383 bytes (380 KB)
downloaded 380 KB

* installing *source* package 'DelayedArray' ...
** using staged installation
** libs
gcc  -I"C:/PROGRA~1/R/R-42~1.2/include" -DNDEBUG  -I'C:/Users/Peng Chen/AppData/Local/R/win-library/4.2/S4Vectors/include'   -I"c:/rtools42/x86_64-w64-mingw32.static.posix/include"     -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign  -c R_init_DelayedArray.c -o R_init_DelayedArray.o
sh: line 1: gcc: command not found
make: *** [C:/PROGRA~1/R/R-42~1.2/etc/x64/Makeconf:253: R_init_DelayedArray.o] Error 127
ERROR: compilation failed for package 'DelayedArray'
* removing 'C:/Users/Peng Chen/AppData/Local/R/win-library/4.2/DelayedArray'
ERROR: dependency 'DelayedArray' is not available for package 'celldex'
* removing 'C:/Users/Peng Chen/AppData/Local/R/win-library/4.2/celldex'

The downloaded source packages are in
	‘C:\Users\Peng Chen\AppData\Local\Temp\RtmpQlUWYx\downloaded_packages’
Installation paths not writeable, unable to update packages
  path: C:/Program Files/R/R-4.2.2/library
  packages:
    boot, class, codetools, foreign, MASS, spatial, survival
Old packages: 'colorspace', 'dplyr', 'fansi', 'httpuv', 'nlme', 'Rcpp', 'reticulate', 'sourcetools', 'sp',
  'spatstat.explore', 'spatstat.geom', 'spatstat.random', 'tidyr', 'umap', 'utf8', 'vctrs', 'xfun'
Update all/some/none? [a/s/n]:_** 
```

**Comment by chen-peng-1874** [comment]
Thanks! And I have attached the detailed information


Chen Peng

Postdoctoral Scholar - Research Associate

Center for Craniofacial Molecular Biology

Herman Ostrow School of Dentistry

2250 Alcazar St. CSA 119

Los Angeles, CA 90089

________________________________
发件人: Peter Hickey ***@***.***>
发送时间: Thursday, February 2, 2023 4:42:43 PM
收件人: PeteHaitch/DelayedMatrixStats ***@***.***>
抄送: Peng Chen ***@***.***>; Author ***@***.***>
主题: Re: [PeteHaitch/DelayedMatrixStats] ERROR: compilation failed for package 'DelayedArray' (Issue #89)


The package is building fine on the Bioconductor build system, so I'll need more information to be able to help,

3.16<https://urldefense.com/v3/__https://www.bioconductor.org/checkResults/3.16/bioc-LATEST/DelayedMatrixStats/__;!!LIr3w8kk_Xxm!qokpHC7WyKyoFoq1OINVUQNMGIH9BIl7-ldMH7iiCOXhWMVCSze64rXhn71g7az_qMSJUHUXTz5kr_ZqKGNYTyn7Mg$>
3.17<https://urldefense.com/v3/__https://www.bioconductor.org/checkResults/3.17/bioc-LATEST/DelayedMatrixStats/__;!!LIr3w8kk_Xxm!qokpHC7WyKyoFoq1OINVUQNMGIH9BIl7-ldMH7iiCOXhWMVCSze64rXhn71g7az_qMSJUHUXTz5kr_ZqKGNeJ0XwgA$>

―

**Comment by LTLA** [comment]
Looks like there are file access issues on the Windows builder (see [here](http://bioconductor.org/checkResults/release/bioc-LATEST/DelayedArray/palomino4-buildsrc.html)). Maybe the builder ran out of disk space.

TBH this is better posted on the [**DelayedArray**](https://github.com/Bioconductor/DelayedArray) repo, but maybe we can just ping @hpages here.

**Comment by PeteHaitch** [comment]
@LTLA has posted much what I was about to post, but see below

The problem is actually with **DelayedArray**:

```
ERROR: compilation failed for package 'DelayedArray'
```

Looking at the [Bioconductor 3.16 build reports for it](https://www.bioconductor.org/checkResults/3.16/bioc-LATEST/DelayedArray/) we can see that the most recent build failed specifically on Windows (which I think you are on based on what you posted).

I suggest trying to do `BiocManager::install("DelayedArray")` and when asked whether you want to install the 'binary' or 'source' package that you try installing the binary (which will be slightly older but should install).

```
  There is a binary version available but the source version is later:
             binary source needs_compilation
DelayedArray 0.23.2 0.24.0              TRUE
```

**Comment by chen-peng-1874** [comment]
> 
Thanks, but I have enough disk space.

**Comment by chen-peng-1874** [comment]
> @LTLA has posted much what I was about to post, but see below
> 
> The problem is actually with **DelayedArray**:
> 
> ```
> ERROR: compilation failed for package 'DelayedArray'
> ```
> 
> Looking at the [Bioconductor 3.16 build reports for it](https://www.bioconductor.org/checkResults/3.16/bioc-LATEST/DelayedArray/) we can see that the most recent build failed specifically on Windows (which I think you are on based on what you posted).
> 
> I suggest trying to do `BiocManager::install("DelayedArray")` and when asked whether you want to install the 'binary' or 'source' package that you try installing the binary (which will be slightly older but should install).
> 
> ```
>   There is a binary version available but the source version is later:
>              binary source needs_compilation
> DelayedArray 0.23.2 0.24.0              TRUE
> ```

YES, I am on Windows, and I tried installing "DelayedArray", but this installation is still a problem.
Here is the code:
_**BiocManager::install("DelayedArray")
Update all/some/none? [a/s/n]: 
a

  There are binary versions available but the source versions are later:
             binary   source needs_compilation
nlme        3.1-161  3.1-162              TRUE
sourcetools   0.1.7  0.1.7-1              TRUE
umap        0.2.9.0 0.2.10.0              TRUE
utf8          1.2.2    1.2.3              TRUE
xfun           0.36     0.37              TRUE

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.2/colorspace_2.1-0.zip'
Content type 'application/zip' length 2624951 bytes (2.5 MB)
downloaded 2.5 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.2/dplyr_1.1.0.zip'
Content type 'application/zip' length 1548293 bytes (1.5 MB)
downloaded 1.5 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.2/fansi_1.0.4.zip'
Content type 'application/zip' length 313271 bytes (305 KB)
downloaded 305 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.2/httpuv_1.6.8.zip'
Content type 'application/zip' length 979339 bytes (956 KB)
downloaded 956 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.2/Rcpp_1.0.10.zip'
Content type 'application/zip' length 2819280 bytes (2.7 MB)
downloaded 2.7 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.2/reticulate_1.28.zip'
Content type 'application/zip' length 2069262 bytes (2.0 MB)
downloaded 2.0 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.2/sp_1.6-0.zip'
Content type 'application/zip' length 1790638 bytes (1.7 MB)
downloaded 1.7 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.2/spatstat.explore_3.0-6.zip'
Content type 'application/zip' length 3210352 bytes (3.1 MB)
downloaded 3.1 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.2/spatstat.geom_3.0-6.zip'
Content type 'application/zip' length 3879604 bytes (3.7 MB)
downloaded 3.7 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.2/spatstat.random_3.1-3.zip'
Content type 'application/zip' length 1131851 bytes (1.1 MB)
downloaded 1.1 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.2/tidyr_1.3.0.zip'
Content type 'application/zip' length 1292447 bytes (1.2 MB)
downloaded 1.2 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.2/vctrs_0.5.2.zip'
Content type 'application/zip' length 1378546 bytes (1.3 MB)
downloaded 1.3 MB

package ‘colorspace’ successfully unpacked and MD5 sums checked
package ‘dplyr’ successfully unpacked and MD5 sums checked
package ‘fansi’ successfully unpacked and MD5 sums checked
package ‘httpuv’ successfully unpacked and MD5 sums checked
package ‘Rcpp’ successfully unpacked and MD5 sums checked
package ‘reticulate’ successfully unpacked and MD5 sums checked
package ‘sp’ successfully unpacked and MD5 sums checked
package ‘spatstat.explore’ successfully unpacked and MD5 sums checked
package ‘spatstat.geom’ successfully unpacked and MD5 sums checked
package ‘spatstat.random’ successfully unpacked and MD5 sums checked
package ‘tidyr’ successfully unpacked and MD5 sums checked
package ‘vctrs’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\Peng Chen\AppData\Local\Temp\RtmpQlUWYx\downloaded_packages
installing the source packages ‘nlme’, ‘sourcetools’, ‘umap’, ‘utf8’, ‘xfun’

trying URL 'https://cran.rstudio.com/src/contrib/nlme_3.1-162.tar.gz'
Content type 'application/x-gzip' length 848546 bytes (828 KB)
downloaded 828 KB

trying URL 'https://cran.rstudio.com/src/contrib/sourcetools_0.1.7-1.tar.gz'
Content type 'application/x-gzip' length 24095 bytes (23 KB)
downloaded 23 KB

trying URL 'https://cran.rstudio.com/src/contrib/umap_0.2.10.0.tar.gz'
Content type 'application/x-gzip' length 82451 bytes (80 KB)
downloaded 80 KB

trying URL 'https://cran.rstudio.com/src/contrib/utf8_1.2.3.tar.gz'
Content type 'application/x-gzip' length 241412 bytes (235 KB)
downloaded 235 KB

trying URL 'https://cran.rstudio.com/src/contrib/xfun_0.37.tar.gz'
Content type 'application/x-gzip' length 130063 bytes (127 KB)
downloaded 127 KB

* installing *source* package 'nlme' ...
** package 'nlme' successfully unpacked and MD5 sums checked
** using staged installation
** libs
gfortran  -fno-optimize-sibling-calls    -O2  -mfpmath=sse -msse2 -mstackrealign  -c chol.f -o chol.o
make: gfortran: No such file or directory
make: *** [C:/PROGRA~1/R/R-42~1.2/etc/x64/Makeconf:277: chol.o] Error 127
ERROR: compilation failed for package 'nlme'
* removing 'C:/Users/Peng Chen/AppData/Local/R/win-library/4.2/nlme'
* restoring previous 'C:/Users/Peng Chen/AppData/Local/R/win-library/4.2/nlme'
* installing *source* package 'sourcetools' ...
** package 'sourcetools' successfully unpacked and MD5 sums checked
** using staged installation
** libs
g++ -std=gnu++11  -I"C:/PROGRA~1/R/R-42~1.2/include" -DNDEBUG -I../inst/include    -I"c:/rtools42/x86_64-w64-mingw32.static.posix/include"     -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c Reader.cpp -o Reader.o
sh: line 1: g++: command not found
make: *** [C:/PROGRA~1/R/R-42~1.2/etc/x64/Makeconf:260: Reader.o] Error 127
ERROR: compilation failed for package 'sourcetools'
* removing 'C:/Users/Peng Chen/AppData/Local/R/win-library/4.2/sourcetools'
* restoring previous 'C:/Users/Peng Chen/AppData/Local/R/win-library/4.2/sourcetools'
* installing *source* package 'umap' ...
** package 'umap' successfully unpacked and MD5 sums checked
** using staged installation
** libs
g++ -std=gnu++11  -I"C:/PROGRA~1/R/R-42~1.2/include" -DNDEBUG  -I'C:/Users/Peng Chen/AppData/Local/R/win-library/4.2/Rcpp/include'   -I"c:/rtools42/x86_64-w64-mingw32.static.posix/include"     -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c RcppExports.cpp -o RcppExports.o
sh: line 1: g++: command not found
make: *** [C:/PROGRA~1/R/R-42~1.2/etc/x64/Makeconf:260: RcppExports.o] Error 127
ERROR: compilation failed for package 'umap'
* removing 'C:/Users/Peng Chen/AppData/Local/R/win-library/4.2/umap'
* restoring previous 'C:/Users/Peng Chen/AppData/Local/R/win-library/4.2/umap'
* installing *source* package 'utf8' ...
** package 'utf8' successfully unpacked and MD5 sums checked
** using staged installation
** libs
gcc  -I"C:/PROGRA~1/R/R-42~1.2/include" -DNDEBUG     -I"c:/rtools42/x86_64-w64-mingw32.static.posix/include"  -Iutf8lite/src   -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign  -c as_utf8.c -o as_utf8.o
sh: line 1: gcc: command not found
make: *** [C:/PROGRA~1/R/R-42~1.2/etc/x64/Makeconf:253: as_utf8.o] Error 127
ERROR: compilation failed for package 'utf8'
* removing 'C:/Users/Peng Chen/AppData/Local/R/win-library/4.2/utf8'
* restoring previous 'C:/Users/Peng Chen/AppData/Local/R/win-library/4.2/utf8'
* installing *source* package 'xfun' ...
** package 'xfun' successfully unpacked and MD5 sums checked
** using staged installation
** libs
gcc  -I"C:/PROGRA~1/R/R-42~1.2/include" -DNDEBUG     -I"c:/rtools42/x86_64-w64-mingw32.static.posix/include"     -O2 -Wall  -std=gnu99 -mfpmath=sse -msse2 -mstackrealign  -c base64.c -o base64.o
sh: line 1: gcc: command not found
make: *** [C:/PROGRA~1/R/R-42~1.2/etc/x64/Makeconf:253: base64.o] Error 127
ERROR: compilation failed for package 'xfun'
* removing 'C:/Users/Peng Chen/AppData/Local/R/win-library/4.2/xfun'
* restoring previous 'C:/Users/Peng Chen/AppData/Local/R/win-library/4.2/xfun'

The downloaded source packages are in
	‘C:\Users\Peng Chen\AppData\Local\Temp\RtmpQlUWYx\downloaded_packages’
Warning messages:
1: In install.packages(...) :
  installation of package ‘DelayedArray’ had non-zero exit status
2: In install.packages(...) :
  installation of package ‘celldex’ had non-zero exit status
3: In install.packages(update[instlib == l, "Package"], l, repos = repos,  :
  installation of package ‘nlme’ had non-zero exit status
4: In install.packages(update[instlib == l, "Package"], l, repos = repos,  :
  installation of package ‘sourcetools’ had non-zero exit status
5: In install.packages(update[instlib == l, "Package"], l, repos = repos,  :
  installation of package ‘umap’ had non-zero exit status
6: In install.packages(update[instlib == l, "Package"], l, repos = repos,  :
  installation of package ‘utf8’ had non-zero exit status
7: In install.packages(update[instlib == l, "Package"], l, repos = repos,  :
  installation of package ‘xfun’ had non-zero exit status**_

**Comment by hpages** [comment]
Wait, you don't seem to have any compilers on your machine, how do you expect to install packages from source?

Just install the binaries (this is the default) and you should be fine. That's what 98.5% of Windows users do.

**Comment by chen-peng-1874** [comment]
> Wait, you don't seem to have any compilers on your machine, how do you expect to install packages from source?
> 
> Just install the binaries (this is the default) and you should be fine. That's what 98.5% of Windows users do.

WOW! I know it! Thank you!

**Comment by chen-peng-1874** [comment]
Successfully solved by installing binary packages. Thanks all!
