### ISSUE TITLE
matrixStats 1.0.0: Breaking changes

### ISSUE THREAD

**Issue by HenrikBengtsson** [PeteHaitch/DelayedMatrixStats#91]
Hello, **[matrixStats](cran.r-project.org/package=matrixStats)** 1.0.0 is now on CRAN (as 2023-06-02).  It comes with the following significant changes:

1. `useNames = TRUE` is the new default for all functions.

2. `colQuantiles()` and `rowQuantiles()` only sets quantile percentage names when `useNames = TRUE`, to align with how argument names of `stats::quantile()` works in base R. Previously, `useNames = FALSE` also had such names attributes.

**Comment by PeteHaitch** [comment]
Thanks Henrik.
I'll await how we resolve this in https://github.com/Bioconductor/MatrixGenerics/issues/31 before updating **DelayedMatrixStats**.

**Comment by LTLA** [comment]
Looks like you need to propagate `useNames = useNames` at

https://github.com/PeteHaitch/DelayedMatrixStats/blob/166420114b974ca628ca900994717785ffbbdf99/R/utils.R#L316

Otherwise, user-provided overrides aren't respected when the dispatcher decides it can skip block processing.

**Comment by PeteHaitch** [comment]
@LTLA Won't the user-provided `useNames` be passed via `...`?

**Comment by LTLA** [comment]
No, because `.smart_seed_dispatcher()` has an explicit `useNames` argument, so it gets pulled out of the `...`.

**Comment by PeteHaitch** [comment]
Addressed as part of https://github.com/PeteHaitch/DelayedMatrixStats/pull/96
