### ISSUE TITLE
Broken Travis CI image in README

### ISSUE THREAD

**Issue by ryandesign** [PeteHaitch/DelayedMatrixStats#98]
https://github.com/PeteHaitch/DelayedMatrixStats/blob/409a7fa3ed81b1f47566707138ee4c7bf4f607d4/README.md?plain=1#L6-L7

This is a broken image and clicking the link says:

> This is not an active repository
> 
> You don't have sufficient rights to enable this repo on Travis.
> Please contact the admin to enable it or to receive admin rights yourself.

**Comment by PeteHaitch** [comment]
These were stale and so I've removed them in 67d9dfd2b60b56aecc8048bec41991666134e6f4
This software is developed as part of Bioconductor and so is checked by its daily build system which is enough for my current purpose.
